// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYm0CTTWyNsqH8vxL_xRcVGAs-gDIhIk4',
    appId: '1:312079939945:web:e23597d7771279194025f8',
    messagingSenderId: '312079939945',
    projectId: 'ui-lab4-flutter-cpp',
    authDomain: 'ui-lab4-flutter-cpp.firebaseapp.com',
    storageBucket: 'ui-lab4-flutter-cpp.firebasestorage.app',
    measurementId: 'G-BGQ1VB7HT8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAMmQNDPsOjfpMktv4qWN3zOrW3vr4cRAM',
    appId: '1:312079939945:android:dc4ff9f6d24f0ea14025f8',
    messagingSenderId: '312079939945',
    projectId: 'ui-lab4-flutter-cpp',
    storageBucket: 'ui-lab4-flutter-cpp.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYm0CTTWyNsqH8vxL_xRcVGAs-gDIhIk4',
    appId: '1:312079939945:web:bf1d163d61e609bf4025f8',
    messagingSenderId: '312079939945',
    projectId: 'ui-lab4-flutter-cpp',
    authDomain: 'ui-lab4-flutter-cpp.firebaseapp.com',
    storageBucket: 'ui-lab4-flutter-cpp.firebasestorage.app',
    measurementId: 'G-7FYWF2RW4T',
  );

}